#!/bin/bash
wallpaper_path="/usr/share/wallpapers/novsu_wallpaper/contents/1920x1080.png"

# Установка обоев
qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript '
var allDesktops = desktops();
print (allDesktops);
for (i=0;i<allDesktops.length;i++) {
    d = allDesktops[i];
    d.wallpaperPlugin = "org.kde.image";
    d.currentConfigGroup = Array("Wallpaper", "org.kde.image", "General");
    d.writeConfig("Image", "file://'"$wallpaper_path"'");
}'
